version: "3.8"
services:
  web:
    build: . # relative location of the directory wher Dockerfile is present. We use . since it is in root directory
    volumes:
      - .:/code
    image: states_and_districts-web:django
    command: "sh /code/start.sh"
    ports:
      - "8000:8000"