# Generated by Django 4.2.1 on 2023-05-07 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="States",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="State Name"
                    ),
                ),
                (
                    "Is_Union_Territory",
                    models.BooleanField(
                        default=False, verbose_name="Is Union Territory"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "States",
                "ordering": ["Is_Union_Territory", "Name"],
                "indexes": [
                    models.Index(
                        fields=["Name", "Is_Union_Territory"], name="state_index"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Districts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Name",
                    models.CharField(max_length=200, verbose_name="District Name"),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_districts",
                        related_query_name="state_district",
                        to="app.states",
                        verbose_name="State",
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ["state", "Name"],
                "indexes": [
                    models.Index(fields=["Name", "state"], name="district_index")
                ],
                "unique_together": {("Name", "state")},
            },
        ),
    ]
